### ISSUE TITLE
cannot make it work

### ISSUE THREAD

**Issue by daviddanko** [Nesousx/nesatmo#1]
Hi,

I'm having troubles with making this work. I've done everything; generated the client id and secret on the netatmo dashboard, have a working influxdb and grafana instance and have the correct credentials. When I start the container, it doesn't generate any logs.

$ docker compose up
[+] Running 2/2
 ⠿ Network docker_default  Created  0.0s
 ⠿ Container nesatmo       Created  0.1s
Attaching to nesatmo

I can see some entries in in the influx tho:

[httpd] 192.168.0.168, 172.18.0.1, 172.18.0.1,172.18.0.1 - admin [16/Aug/2022:20:42:24 +0000] "POST /query?db=influx_db&epoch=ms HTTP/1.1 {'q': 'SELECT mean("value") FROM "humidity" WHERE ("station" = 'nesoweath' AND "sensor" = 'outdoor') AND time >= now() - 24h and time <= now() GROUP BY time(15m) fill(null)'}" 200 57 "-" "Grafana/9.1.0" eef8bc34-1da3-11ed-82f5-0242ac120008 643
ts=2022-08-16T20:42:24.452103Z lvl=info msg="Executing query" log_id=0cLzVnnG000 service=query query="SELECT mean(value) FROM influx_db.autogen.temperature WHERE (station = 'nesoweath' AND sensor = 'indoor') AND time >= now() - 1d AND time <= now() GROUP BY time(1m), station_name"
[httpd] 192.168.0.168, 172.18.0.1, 172.18.0.1,172.18.0.1 - admin [16/Aug/2022:20:42:24 +0000] "POST /query?db=influx_db&epoch=ms HTTP/1.1 {'q': 'SELECT mean("value") FROM "temperature" WHERE ("station" = 'nesoweath' AND "sensor" = 'indoor') AND time >= now() - 24h and time <= now() GROUP BY time(1m), "station_name" fill(null)'}" 200 57 "-" "Grafana/9.1.0" eef8ec87-1da3-11ed-82f6-0242ac120008 352
ts=2022-08-16T20:42:24.454821Z lvl=info msg="Executing query" log_id=0cLzVnnG000 service=query query="SELECT mean(value) FROM influx_db.autogen.temperature WHERE (station = 'nesoweath' AND sensor = 'outdoor') AND time >= now() - 1d AND time <= now() GROUP BY time(1m), station_name"
[httpd] 192.168.0.168, 172.18.0.1, 172.18.0.1,172.18.0.1 - admin [16/Aug/2022:20:42:24 +0000] "POST /query?db=influx_db&epoch=ms 
HTTP/1.1 {'q': 'SELECT mean("value") FROM "temperature" WHERE ("station" = 'nesoweath' AND "sensor" = 'outdoor') AND time >= now() - 24h and time <= now() GROUP BY time(1m), "station_name" fill(null)'}" 200 57 "-" "Grafana/9.1.0" eef95209-1da3-11ed-82f7-0242ac120008 478
ts=2022-08-16T20:42:27.021717Z lvl=info msg="Executing query" log_id=0cLzVnnG000 service=query query="SHOW TAG KEYS ON influx_db WHERE _name = 'temperature'"

Unfortunately, in grafana I can see only "no data". 

I don't quite understand the following instruction:

Search and replace the following elements :
"nesoweath" by your station's name ;
"indoor" by your indoor's sensor's name ;
"outdoor" by your outdoor's sensor's name.

Do I have to replace those terms in the influx query in grafana? If so, where can I find my names? I only have a couple of thermostats. 

Thanks in advance.

**Comment by Nesousx** [comment]
Hi,

The container doesn't generate logs, unfortunately.

You have to replace "nesoweath", "indoor" and "outdoor" in the Grafana template file (you can Edit the Dashboard directly from Grafana website). You can find the name of your own station and sensors in the official netatmo webpage and/or application.

Let me know if it helps.

**Comment by daviddanko** [comment]
Hi Denis,

I have 3 thermostats: Bedroom, Living Room, Children's Room.

Can you help me understand what is the nesoweath and where exactly can I find it's name in my app/netatmo webpage? Is it some kind of outside sensor? Because I don't have one. Therefore I don't know what to do with that element in the query.

This is the default query for the Temperature Inside table:

SELECT mean("value") FROM "temperature" WHERE ("station" = 'nesoweath' AND "sensor" = 'indoor') AND $timeFilter GROUP BY time($interval), "station_name" fill(null)

I edited the WHERE clause to ("station" = 'nesoweath' AND "sensor" = 'Bedroom') and also simply to ("sensor" = 'Bedroom'), but still 'no data' is showing up.

**Comment by Nesousx** [comment]
Ok, first of all, what is your exact device? Show me the product page, pls.

This container, is not for themostat but for weather station.

**Comment by daviddanko** [comment]
Alright, then I know why it's not working. So I have 3 of the radiator valves. In my country, we call them thermostats, so my mistake.
![Screenshot 2022-08-21 213651](https://user-images.githubusercontent.com/111394221/185808094-abbc869f-02fd-4916-b22d-a418d8afbae8.png)
![Screenshot 2022-08-21 213759](https://user-images.githubusercontent.com/111394221/185808097-b63c9e7d-b413-44bb-96db-be857c31ef3b.png)

**Comment by Nesousx** [comment]
Yup, that's it, wrong product, sorry !
